version: "3.8"  # Always define a version for clarity

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./scr:/app/scr
      - ./index.js:/app/index.js
      - ./uploads:/app/uploads
      - ./.env:/app/.env   # add leading dot to make sure it mounts correctly
    ports:
      - "9899:9899"
    networks:
      - mysql-phpmyadmin
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}

  mysql:
    image: mysql:8.0 # It's good to lock a version
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8090:80"
    environment:
      - PMA_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
